# Generated by Django 6.0.3 on 2026-03-24 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='settings',
        ),
    ]
