# Generated by Django 6.0.3 on 2026-04-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_replace_useractivitylog_with_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('register', 'Register'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('inventory_created', 'Inventory Created'), ('inventory_updated', 'Inventory Updated'), ('inventory_deleted', 'Inventory Deleted'), ('transaction_created', 'Transaction Created'), ('transaction_deleted', 'Transaction Deleted'), ('other', 'Other')], max_length=50),
        ),
    ]
