# Generated by Django 6.0.3 on 2026-03-24 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_product_category_alter_product_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('product_description', models.CharField(max_length=255)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('stock_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reorder_status', models.CharField(default='No', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
