# Generated by Django 6.0.3 on 2026-03-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product_description',
        ),
    ]
