# Generated by Django 6.0.3 on 2026-03-31 03:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_unique_together'),
        ('products', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='products.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_on_hand',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='quantity_on_hand_non_negative'),
        ),
    ]
