# Generated by Django 6.0.3 on 2026-04-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='reorder_status',
            field=models.CharField(choices=[('LOW', 'LOW'), ('No', 'No'), ('NO STOCK', 'NO STOCK')], db_index=True, default='No', max_length=8),
        ),
    ]
