# Generated by Django 6.0.3 on 2026-03-30 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_order_date_and_more'),
        ('transactions', '0003_transaction_items_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Receive', 'Receive'), ('Sale', 'Sale')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('transaction_type__in', ['Receive', 'Sale'])), name='transaction_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='transaction_item_quantity_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost_per_unit__gt', 0)), name='transaction_item_cost_positive'),
        ),
    ]
