# Generated by Django 6.0.3 on 2026-03-25 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(help_text='Physical barcode scanned from the product. Must be unique.', max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Fasteners', 'Fasteners'), ('Accessories', 'Accessories')], default='Fasteners', max_length=255)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('supplier', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
