# Generated by Django 6.0.3 on 2026-03-28 03:03

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_collation='utf8mb4_bin', default=products.models.generate_barcode, help_text='Barcode format: SN-XXXXXX', max_length=20, unique=True),
        ),
    ]
