# Generated by Django 6.0.3 on 2026-03-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_collation='utf8mb4_bin', help_text='Physical barcode scanned from the product. Must be unique.', max_length=20, unique=True),
        ),
    ]
