# Generated by Django 6.0.3 on 2026-03-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_name_product_supplier_remove_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fasteners', 'Fasteners'), ('Accessories', 'Accessories')], default='Fasteners', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=5),
        ),
    ]
