# Generated by Django 6.0.3 on 2026-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category_alter_product_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode ID (3-15 alphanumeric chars)', max_length=15, null=True, unique=True),
        ),
    ]
