# Generated by Django 6.0.3 on 2026-03-24 09:47

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=products.models.generate_barcode, help_text='Barcode ID (3-15 alphanumeric chars). Randomly generated if not provided.', max_length=15, unique=True),
        ),
    ]
